- name: Play1
  hosts: qa
  become: yes
  tasks:
    - name: move to tmp folder
      shell: cd /tmp
    - name: download the files required
      shell: wget https://apt.puppet.com/puppet7-release-focal.deb
    - name: add to DPKG
      shell: dpkg -i puppet7-release-focal.deb
    - name: install the package
      apt:
        update_cache: yes
        name: puppetserver
        state: present
