name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      env:
        DOCKER_USER: ${{(secrets.DOCKER_USER)}}
        DOCKER_PASSWORD: ${{(secrets.DOCKER_PASSWORD)}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - uses: actions/build-push-action@v3
      with:
        context: .
        push: true
        tags: smenon94/sampleapp:v4
